server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_inmobiliaria?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver_class_name=com.mysql.cj.jdbc.Driver

spring.jpa.database_plataform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=gestion-inmobiliaria-backend


# --- CONFIGURACIÓN DE CORREO (Ejemplo Gmail) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# ¡Ojo! Aquí pon el correo de la inmobiliaria
spring.mail.username=tu_correo_inmobiliaria@gmail.com
# Usa una "Contraseña de aplicación" de Google, no tu contraseña normal
spring.mail.password=tu_contraseña_generada
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true